# Generated by Django 4.1.1 on 2022-09-19 10:28

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=9, prefix='', primary_key=True, serialize=False),
        ),
    ]
