# Generated by Django 4.1.1 on 2022-09-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='add_desc',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='det_desc',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gen_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
