# Generated by Django 4.1.1 on 2022-09-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
