# Generated by Django 4.1.1 on 2022-09-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_city_service_customer_gender_customer_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('PNS', 'Prefer not to say')], max_length=3, null=True),
        ),
    ]
