# Generated by Django 4.1.1 on 2022-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_user_customer_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproduct',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='service',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='VendorProduct',
        ),
    ]
